export const columnsMapping = [
  {
    id: 'FacilityName',
    fieldId: 'IA_P_Facility',
    translationId: 'IM_IA_Facility',
    isSelected: true,
  },
  {
    id: 'IncidentDateTime',
    fieldId: 'II_P_IncidentDate',
    translationId: 'IM_IA_IncidentDate',
    isSelected: true,
  },
  {
    id: 'ReportedDate',
    fieldId: 'IM_IA_ReportedDate',
    translationId: 'IM_IA_ReportedDate',
    isSelected: true,
  },
  {
    id: 'IncidentNo',
    fieldId: 'IA_P_IncidentNumber',
    translationId: 'IM_IA_IncidentNumber',
    isSelected: true,
  },
  {
    id: 'IncidentDetail',
    fieldId: 'IA_P_IncidentDetails',
    translationId: 'IM_IA_IncidentDetails',
    isSelected: true,
  },
  {
    id: 'BriefDescriptionOfIncident',
    fieldId: 'IA_P_BriefDescriptionofIncident',
    translationId: 'IM_IA_BriefDescriptionofIncident',
    isSelected: true,
  },
  {
    id: 'IncidentType',
    fieldId: 'IA_P_IncidentType',
    translationId: 'IM_IA_IncidentType',
    isSelected: true,
  },
  {
    id: 'DepartmentName',
    tfieldId: 'II_P_Department',
    translationId: 'IM_IA_Department',
    isSelected: true,
  },
  {
    id: 'ReportedBy',
    fieldId: "IA_P_ReportedBy",
    translationId: 'IM_IA_ReportedBy',
    isSelected: true,
  },
  { id: 'TAT',
   fieldId: "IA_P_TAT",
   translationId: 'IM_IA_TAT',
   isSelected: true,
 },
  { id: 'TATCompliance',
   fieldId: "IA_P_TATCompliance",
   translationId: 'IM_IA_TATCompliance',
   isSelected: true,
 },
   { id: 'IncidentStatus',
    fieldId: "IA_P_IncidentStatus",
    translationId: 'IM_IA_IncidentStatus',
    isSelected: true,
  },


  { id: 'AffectedCategory',
    fieldId: "IA_P_AffectedCategory",
    translationId: 'IM_IA_AffectedCategory',
    isSelected: true,
  },
  { id: 'AffectedCategoryCode',
    fieldId: "IA_P_AffectedCategoryCode",
    translationId: 'IM_IA_AffectedCategoryCode',
    isSelected: true,
  },
  { id: 'MainCategoryCode',
    fieldId: "IA_P_MainCategoryCode",
    translationId: 'IM_IA_MainCategoryCode',
    isSelected: true,
  },
  { id: 'SubCategoryCode',
    fieldId: "IA_P_SubCategoryCode",
    translationId: 'IM_IA_SubCategoryCode',
    isSelected: true,
  },
  { id: 'IncidentDetailCode',
    fieldId: "IA_P_IncidentDetailsCode",
    translationId: 'IM_IA_IncidentDetailsCode',
    isSelected: true,
  },

];


