export const columnsMapping = [
  {
    id: 'Facility',
    fieldId: 'IA_P_Facility',
    translationId: 'IM_IA_Facility',
    isSelected: true,
  },
  {
    id: 'Incident Date',
    fieldId: 'II_P_IncidentDate',
    translationId: 'IM_IA_IncidentDate',
    isSelected: true,
  },
  {
    id: 'Reported Date',
    fieldId: 'IA_P_ReportedDate',
    translationId: 'IM_IA_ReportedDate',
    isSelected: true,
  },
  {
    id: 'Incident Number',
    fieldId: 'IA_P_IncidentNumber',
    translationId: 'IM_IA_IncidentNumber',
    isSelected: true,
  },
  {
    id: 'Incident Details',
    fieldId: 'IA_P_IncidentDetails',
    translationId: 'IM_IA_IncidentDetails',
    isSelected: true,
  },
  {
    id: 'Incident Type',
    fieldId: 'IA_P_IncidentType',
    translationId: 'IM_IA_IncidentType',
    isSelected: true,
  },
  {
    id: 'Department',
    tfieldId: 'II_P_Department',
    translationId: 'IM_IA_Department',
    isSelected: true,
  },
  {
    id: 'Approved Date',
    fieldId: "IA_P_ApprovedDate",
    translationId: 'IM_IA_ApprovedDate',
    isSelected: true,
  },


  {
    id: 'Approval Type',
    fieldId: "IA_P_ApprovalType",
    translationId: 'IM_IA_ApprovalType',
    isSelected: true,
  },
  { id: 'TAT',
    fieldId: "IA_P_TAT",
    translationId: 'IM_IA_TAT',
    isSelected: true,
  },
   { id: 'TAT Compliance',
    fieldId: "IA_P_TATCompliance",
    translationId: 'IM_IA_TATCompliance',
    isSelected: true,
  },
   { id: 'Incident Status',
    fieldId: "IA_P_IncidentStatus",
    translationId: 'IM_IA_IncidentStatus',
    isSelected: true,
  },

  { id: 'AffectedCategory',
    fieldId: "IA_P_AffectedCategory",
    translationId: 'IM_IA_AffectedCategory',
    isSelected: true,
  },
  { id: 'Affected Category Code',
    fieldId: "IA_P_AffectedCategoryCode",
    translationId: 'IM_IA_AffectedCategoryCode',
    isSelected: true,
  },
  { id: 'Main Category Code',
    fieldId: "IA_P_MainCategoryCode",
    translationId: 'IM_IA_MainCategoryCode',
    isSelected: true,
  },
  { id: 'Sub Category Code',
    fieldId: "IA_P_SubCategoryCode",
    translationId: 'IM_IA_SubCategoryCode',
    isSelected: true,
  },
  { id: 'Incident Details Code',
    fieldId: "IA_P_IncidentDetailsCode",
    translationId: 'IM_IA_IncidentDetailsCode',
    isSelected: true,
  },


];


