export const routeToNameMapping = {
  '/': 'Home',
  '/main-master': 'Main Master',
  '/ad-master': 'AD Master',
  '/main-master/staff-master': 'Staff Master',
  // "/mail-credential": "Mail Credential",
  '/staff-master': 'Staff Master',
  '/incident-management/report-incident': 'Report Incident',
  '/email-editor': 'Email Editor',
  '/contact-info': 'Contact Information',
  '/department-unit-master': 'Department/Unit Master',
  '/physician-demography': 'Physician Demography',
  '/physician-demography-verifications': 'Physician Demography Verifications',
  '/application-role': 'Application Role',
  '/page-utilities': 'Page Utilities',
  '/incident-submaster': 'Incident Submaster',
  '/incident-category': 'Incident Category',
  '/incident-risk-level-calculation': 'Incident Risk Level Calculation',
  '/notification-master': 'Notification Master',
  '/search-incident': 'Search Incident',
  '/incident-approval': 'Incident Approval',
  '/incident-investigation': 'Incident Investigation',
  '/opinions': 'Opinions',
  '/incident-investigation-approval': 'Incident Investigation Approval',
  '/incident-closure': 'Incident Closure',
  '/root-cause-analysis': 'Root Cause Analysis',
  '/actions': 'Actions',
  '/custom-dashboard': 'Custom Dashboard',
  '/admin-dashboard': 'Admin Dashboard',
  '/incidentdashboard-dashboardfilter': 'Incident Dashboard Filter',
};
