export const columnsMapping = [
  {
    id: 'FacilityName',
    fieldId: 'SI_P_Facility',
    translationId: 'IM_SI_Facility',
    isSelected: true,
  },
  {
    id: 'ReportedDate',
    fieldId: 'SI_P_ReportedDate',
    translationId: 'IM_SI_ReportedDate',
    isSelected: true,
  },
  {
    id: 'IncidentDate',
    fieldId: 'SI_P_IncidentDate',
    translationId: 'IM_SI_IncidentDate',
    isSelected: true,
  },
  {
    id: 'IncidentNumber',
    fieldId: 'SI_P_IncidentNumber',
    translationId: 'IM_SI_IncidentNumber',
    isSelected: true,
  },
  {
    id: 'MainCategory',
    fieldId: 'SI_P_IncidentMainCategory',
    translationId: 'IM_SI_IncidentMainCategory',
    isSelected: true,
  },
  {
    id: 'IncidentDetail',
    fieldId: 'SI_P_IncidentDetails',
    translationId: 'IM_SI_IncidentDetails',
    isSelected: true,
  },
  {
    id: 'IncidentType',
    fieldId: 'SI_P_IncidentType',
    translationId: 'IM_SI_IncidentType',
    isSelected: true,
  },
  {
    id: 'Department',
    fieldId: 'SI_P_Department',
    translationId: 'IM_SI_Department',
    isSelected: true,
  },
  {
    id: 'IncidentRiskLevel',
    fieldId: 'SI_P_IncidentRiskLevel',
    translationId: 'IM_SI_IncidentRiskLevel',
    isSelected: true,
  },
  {
    id: 'IncidentHarmLevel',
    fieldId: 'SI_P_HarmLevel',
    translationId: 'IM_SI_HarmLevel',
    isSelected: true,
  },
  {
    id: 'ClosedDate',
    fieldId: 'SI_P_ClosedDate',
    translationId: 'IM_SI_ClosedDate',
    isSelected: true,
  },
  {
    id: 'ClosedBy',
    fieldId: 'SI_P_ClosedBy',
    translationId: 'IM_SI_ClosedBy',
    isSelected: true,
  },
  {
    id: 'RootCause',
    fieldId: 'SI_P_RootCauses',
    translationId: 'IM_SI_RootCauses',
    isSelected: true,
  },
  {
    id: 'LessonLearned',
    fieldId: 'SI_P_LessonsLearned',
    translationId: 'IM_SI_LessonsLearned',
    isSelected: true,
  },
  {
    id: 'ResponsibleStaff',
    fieldId: 'SI_P_ResponsibleStaff',
    translationId: 'IM_SI_ResponsibleStaff',
    isSelected: true,
  },
  
  {
    id: 'DetailedIncidentStatus',
    fieldId: "SI_P_IncidentStatus",
    translationId: 'IM_SI_IncidentStatus',
    isSelected: true,
  },
  {
    id: 'AffectedCategory',
    fieldId: "SI_P_AffectedCategory",
    translationId: 'IM_SI_AffectedCategory',
    isSelected: true,
  },
  {
    id: 'AffectedCategoryCode',
    fieldId: "SI_P_AffectedCategoryCode",
    translationId: 'IM_SI_AffectedCategoryCode',
    isSelected: true,
  },
  {
    id: 'ActionCompletionStatus',
    fieldId: "SI_P_ActionCompletionStatus",
    translationId: 'IM_SI_ActionCompletionStatus',
    isSelected: true,
  },
  //     {
  //   id: 'IncidentDetailCode',
  //   fieldId: "SI_S_IncidentDetailsCode",
  //   translationId: 'IM_RI_IncidentDetailsCode',
  //   isSelected: true,
  // },
  // {
  //   id: 'IsSentinel',
  //   fieldId: "IA_P_IsSentinel",
  //   translationId: 'IM_IA_IsSentinel',
  //   isSelected: true,
  // },
  {
    id: 'OverAllIncidentStatus',
    fieldId: "SI_P_OverallTATCompliance",
    translationId: 'IM_SI_OverallTATCompliance',
    isSelected: true,
  },
  {
    id: 'RequestReceivedDate',
    fieldId: "SI_IH_RequestReceivedDate",
    translationId: 'IM_SI_RequestReceivedDate',
    isSelected: true,
  },

];