export const columnsMapping = [
  {
    id: 'FacilityName',
    fieldId: 'RCA_P_Facility',
    translationId: 'IM_RCA_Facility',
    isSelected: true,
  },
  {
    id: 'IncidentDateTime',
    fieldId: 'RCA_P_IncidentDate',
    translationId: 'IM_RCA_IncidentDate',
    isSelected: true,
  },
  {
    id: 'ReportedDate',
    fieldId: 'RCA_P_ReportedDate',
    translationId: 'IM_RCA_ReportedDate',
    isSelected: true,
  },
  {
    id: 'IncidentNo',
    fieldId: 'RCA_P_IncidentNumber',
    translationId: 'IM_RCA_IncidentNumber',
    isSelected: true,
  },
  {
    id: 'IncidentDetail',
    fieldId: 'RCA_P_IncidentDetails',
    translationId: 'IM_RCA_IncidentDetails',
    isSelected: true,
  },

  {
    id: 'IncidentType',
    fieldId: 'RCA_P_IncidentType',
    translationId: 'IM_RCA_IncidentType',
    isSelected: true,
  },
  {
    id: 'DepartmentName',
    fieldId: 'RCA_P_IncidentDepartment',
    translationId: 'IM_RCA_IncidentDepartment',
    isSelected: true,
  },
  {
    id: 'IncidentLevel',
    fieldId: "RCA_P_IncidentLevel",
    translationId: 'IM_RCA_IncidentLevel',
    isSelected: true,
  },
  { id: 'IncidentStatus',
   fieldId: "RCA_P_RCAStatus",
   translationId: 'IM_RCA_RCAStatus',
   isSelected: true,
 },
  { id: 'TAT',
   fieldId: "RCA_P_TAT",
   translationId: 'IM_RCA_TAT',
   isSelected: true,
 },
   { id: 'TATCompliance',
    fieldId: "RCA_P_TATCompliance",
    translationId: 'IM_RCA_TATCompliance',
    isSelected: true,
  },


  // { id: 'CompletedDate',
  //   fieldId: "RCA_P_CompletedDate",
  //   translationId: 'IM_RCA_CompletedDate',
  //   isSelected: true,
  // },
  // { id: 'CompletedBy',
  //   fieldId: "RCA_P_CompletedBy",
  //   translationId: 'IM_RCA_CompletedBy',
  //   isSelected: true,
  // },
  // { id: '',
  //   fieldId: "RCA_P_IncidentRiskLevel",
  //   translationId: 'IM_RCA_IncidentRiskLevel',
  //   isSelected: true,
  // },
  // { id: '',
  //   fieldId: "RCA_P_TeamInvolvedinPreparingRootCauseAnalysis",
  //   translationId: 'IM_RCA_TeamInvolvedinPreparingRootCauseAnalysis',
  //   isSelected: true,
  // },
  // { id: '',
  //   fieldId: "RCA_P_EventsSequence",
  //   translationId: 'IM_RCA_EventsSequence',
  //   isSelected: true,
  // },
  // { id: '',
  //   fieldId: "RCA_P_FishBone",
  //   translationId: 'IM_RCA_FishBone',
  //   isSelected: true,
  // },
  // { id: '',
  //   fieldId: "RCA_P_MailTo",
  //   translationId: 'IM_RCA_MailTo',
  //   isSelected: true,
  // },
  // { id: '',
  //   fieldId: "RCA_P_Attachment(s)",
  //   translationId: 'IM_IA_IncidentDetailsCode',
  //   isSelected: true,
  // },
  // { id: '',
  //   fieldId: "RCA_P_ExistingAttachment(s)",
  //   translationId: 'IM_RCA_ExistingAttachment(s)',
  //   isSelected: true,
  // },
  // { id: '',
  //   fieldId: "RCA_P_ExistingFishBone",
  //   translationId: 'IM_RCA_ExistingFishBone',
  //   isSelected: true,
  // },
  // { id: '',
  //   fieldId: "",
  //   translationId: 'IM_RCA_SubmittedBy',
  //   isSelected: true,
  // },
  // { id: '',
  //   fieldId: "RCA_P_SubmittedDate",
  //   translationId: 'IM_RCA_SubmittedDate',
  //   isSelected: true,
  // },
  // { id: '',
  //   fieldId: "RCA_P_Question/Answer",
  //   translationId: 'IM_RCA_Question/Answer',
  //   isSelected: true,
  // },
  // { id: '',
  //   fieldId: "RCA_P_ActionPlan",
  //   translationId: 'IM_RCA_ActionPlan',
  //   isSelected: true,
  // },

];


