import React, { useEffect, useState } from "react";
import {
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  Typography,
  Box,
} from "@mui/material";

const ActionDetailCompletedPdf = () => {
  const [data, setData] = useState(null);

//   useEffect(() => {
//     // Simulating an API call
//     fetch("/api/incident-report") // Replace with actual API URL
//       .then((response) => response.json())
//       .then((result) => setData(result))
//       .catch((error) => console.error("Error fetching data:", error));
//   }, []);

  if (!data) {
    return <Typography>Loading...</Typography>;
  }

  return (
    <Box sx={{ width: "80%", margin: "auto", mt: 4 }}>
      {/* Header Section */}
      <Box
        sx={{
          backgroundColor: "#ccc",
          padding: "10px",
          textAlign: "center",
          fontWeight: "bold",
        }}
      >
        Action Detail - Completed
      </Box>

      {/* Incident Details Table */}
      <TableContainer component={Paper} sx={{ mt: 2 }}>
        <Table>
          <TableBody>
            <TableRow>
              <TableCell><b>Incident Number</b></TableCell>
              <TableCell>{data.incidentNumber}</TableCell>
              <TableCell><b>Incident Date</b></TableCell>
              <TableCell>{data.incidentDate}</TableCell>
            </TableRow>

            <TableRow>
              <TableCell><b>Task Assigned</b></TableCell>
              <TableCell>{data.taskAssigned}</TableCell>
              <TableCell><b>Target Date</b></TableCell>
              <TableCell sx={{ backgroundColor: "red", color: "white" }}>
                {data.targetDate}
              </TableCell>
            </TableRow>

            <TableRow>
              <TableCell><b>Comments</b></TableCell>
              <TableCell>{data.comments}</TableCell>
              <TableCell><b>Submitted Date</b></TableCell>
              <TableCell sx={{ backgroundColor: "red", color: "white" }}>
                {data.submittedDate}
              </TableCell>
            </TableRow>

            <TableRow>
              <TableCell><b>Submitted By</b></TableCell>
              <TableCell>{data.submittedBy}</TableCell>
              <TableCell><b>Department/Speciality</b></TableCell>
              <TableCell>{data.department}</TableCell>
            </TableRow>

            <TableRow>
              <TableCell><b>Approved By</b></TableCell>
              <TableCell>{data.approvedBy}</TableCell>
              <TableCell><b>Approved Date</b></TableCell>
              <TableCell>{data.approvedDate}</TableCell>
            </TableRow>

            <TableRow>
              <TableCell><b>Approver Remarks</b></TableCell>
              <TableCell>{data.approverRemarks}</TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </TableContainer>

      {/* Attachments Table */}
      <Typography variant="h6" sx={{ mt: 3 }}>Attachment(s)</Typography>
      <TableContainer component={Paper}>
        <Table>
          <TableHead>
            <TableRow>
              <TableCell><b>S.No</b></TableCell>
              <TableCell><b>Attachment(s)</b></TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {data.attachments.map((attachment, index) => (
              <TableRow key={attachment.id}>
                <TableCell>{index + 1}</TableCell>
                <TableCell>{attachment.name}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>

      {/* Footer Section */}
      <TableContainer component={Paper} sx={{ mt: 2 }}>
        <Table>
          <TableBody>
            <TableRow>
              <TableCell><b>Generated By</b></TableCell>
              <TableCell>{data.generatedBy}</TableCell>
              <TableCell><b>Designation</b></TableCell>
              <TableCell>{data.designation}</TableCell>
            </TableRow>
            <TableRow>
              <TableCell><b>Generated Date</b></TableCell>
              <TableCell>{data.generatedDate}</TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </TableContainer>
    </Box>
  );
};

export default ActionDetailCompletedPdf;
